import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/components/ui/utils'
import { MainNav } from '@/widgets/main-nav/main-nav'
import React from 'react'

const inter = Inter({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <script src="https://telegram.org/js/telegram-web-app.js" defer></script>
    </head>
    <body
      className={cn(`min-h-screen bg-background ${inter.className}`)}
    >
    {children}
    <MainNav />
    </body>
    </html>
  );
}
